### ISSUE TITLE
Write access to timeline?

### ISSUE THREAD

**Issue by EdwardHinkle** [indieweb/microsub#27]
I know Aperture makes channels available as Micropub endpoints. Should this be at least an optional part of the standard? I say this because with something like IndiePaper now, it would be great if an app like Indigenous could (with proper permissions) request a write access token for a given channel, rather than having the user open Aperture, copy the write token for a particular channel and then paste it into Indigenous. You wouldn’t necessarily have to be able to edit/delete tokens, just generate them. And maybe retrieve them based on appId?

**Comment by aaronpk** [comment]
I actually have an [open issue](https://github.com/aaronpk/Aperture/issues/36) on Aperture which would help in this situation. The idea I had was to treat every Aperture channel as its own IndieAuth identity, so that you could log in to Micropub apps and they'd end up posting into the Aperture channel. The cool part of that is the apps wouldn't even know that they're posting into an Aperture channel, they just see it as a Micropub endpoint.

Your idea of just treating some channels as writable is also interesting though. The only trick is I can't picture the user flow of how to actually have the app request and get the permissions for that. Definitely worth further thought though!

**Comment by EdwardHinkle** [comment]
That open issue actually works well. So then the idea would be that Indigenous would support logging in to “any” Micropub endpoint. That makes a lot of sense! That seems like the solution to this issue that can work across the board. That way if Micro.blog supported basic Microsub features, the user could log into a different Micropub endpoint for their “Save for Later” feature.

(Originally published at: https://eddiehinkle.com/2018/06/28/5/reply/)
